"""OCR-noise–aware text matching for product names.

Receipt product names come from Tesseract OCR + regex cleanup, so they are riddled
with letter/number swaps (``COO`` for ``C00``, ``1`` for ``l``, ``5`` for ``S``) and
truncations. This module provides the *comparison* helpers used to find lookalike
products in the database.

Normalization here is **comparison-only**: it produces a throwaway key for ranking and
matching. Original accented Hungarian names are never altered, stored, or returned from
it — accents carry meaning the model reasons over, so callers always surface the raw
name and only use these folds internally.

``normalize`` mirrors the Go backend's ``NormalizeName``
(``backend/internal/service/receipt/normalize.go``) so the two services agree on the
accent-folding key; ``ocr_fold`` goes further and collapses OCR-confusable glyphs.
"""

from __future__ import annotations

from itertools import product as _iproduct

from rapidfuzz import fuzz

# Hungarian accent folding, matching the Go backend's NormalizeName map exactly.
_ACCENTS = {
    "Á": "A",
    "É": "E",
    "Í": "I",
    "Ó": "O",
    "Ö": "O",
    "Ő": "O",
    "Ú": "U",
    "Ü": "U",
    "Ű": "U",
}

# Groups of glyphs that OCR routinely swaps for one another. Each group folds to its
# first member, so every variant collapses to the same comparison key. Built from the
# receipt OCR artifacts seen in the backend's regex cleanup plus the classic confusions.
_CONFUSION_GROUPS = [
    ("0", "O", "Q", "D"),
    ("1", "L", "I", "|"),
    ("5", "S"),
    ("8", "B"),
    ("6", "G"),
    ("2", "Z"),
    ("9", "Q"),
    ("7", "T"),
    ("U", "V"),
]

# Single-glyph fold table derived from the groups above (representative is group[0]).
_FOLD = {member: group[0] for group in _CONFUSION_GROUPS for member in group}

# Multi-character sequences OCR splits or merges; applied before single-glyph folding.
# Each maps a noisy rendering to a canonical sequence.
_MULTI = {
    "RN": "M",
    "VV": "W",
    "CL": "D",
    "NN": "M",
}


def normalize(s: str) -> str:
    """Accent-free, uppercase, punctuation-free key — the Go ``NormalizeName`` port.

    Comparison-only; the original string is never mutated for storage or display.
    """
    out: list[str] = []
    for ch in s.upper().strip():
        ch = _ACCENTS.get(ch, ch)
        if ch.isascii() and (ch.isalnum()):
            out.append(ch)
        elif ch == " ":
            out.append(" ")
    return " ".join("".join(out).split())


def ocr_fold(s: str) -> str:
    """A stronger comparison key: normalize, then collapse OCR-confusable glyphs and
    drop spaces so ``C00``/``COO`` and ``TEJ FOL``/``TEJFOL`` compare equal."""
    key = normalize(s).replace(" ", "")
    for noisy, canon in _MULTI.items():
        key = key.replace(noisy, canon)
    return "".join(_FOLD.get(ch, ch) for ch in key)


def similarity(a: str, b: str) -> float:
    """0–100 similarity between two names, scored on their OCR-folded keys so that
    OCR noise and accents don't depress the match."""
    fa, fb = ocr_fold(a), ocr_fold(b)
    if not fa or not fb:
        return 0.0
    return fuzz.ratio(fa, fb)


def variants(name: str, limit: int = 12) -> list[str]:
    """Plausible de-OCR'd spellings of ``name``, generated by substituting each
    confusable glyph with the other members of its group. Bounded to ``limit`` to
    avoid combinatorial blowup; the original (accented) name is always first."""
    base = name.strip()
    if not base:
        return []

    # Per-position option lists over the uppercased ASCII skeleton; positions with a
    # known confusion expand, everything else stays put.
    upper = base.upper()
    member_to_group = {m: g for g in _CONFUSION_GROUPS for m in g}
    options: list[tuple[str, ...]] = []
    expandable = 0
    for ch in upper:
        group = member_to_group.get(ch)
        if group and expandable < 4:  # cap the number of expanding positions
            options.append(group)
            expandable += 1
        else:
            options.append((ch,))

    seen: list[str] = [base]
    for combo in _iproduct(*options):
        cand = "".join(combo)
        if cand not in seen:
            seen.append(cand)
        if len(seen) >= limit:
            break
    return seen
